/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soda-cans-4e0be610db9646929d8be84491f1a72f
Title: Soda Cans
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model/soda_cans.glb')

 const can1 = <group position={[-138.345, 0, 0.242]}
  rotation={[-Math.PI / 2, 0, 0]}
  scale={[0.819, 0.819, 1]}>
  <mesh
    castShadow
    receiveShadow
    geometry={nodes['Can_01_-_Default_0'].geometry}
    material={materials['01_-_Default']}
  />
  <mesh
    castShadow
    receiveShadow
    geometry={nodes['Can_02_-_Default_0'].geometry}
    material={materials['02_-_Default']}
  />
</group>

 const can2 = <group
  position={[-46.537, 0, 0.242]}
  rotation={[-Math.PI / 2, 0, 0]}
  scale={[0.819, 0.819, 1]}>
  <mesh
    castShadow
    receiveShadow
    geometry={nodes['Can001_03_-_Default_0'].geometry}
    material={materials['03_-_Default']}
  />
  <mesh
    castShadow
    receiveShadow
    geometry={nodes['Can001_02_-_Default_0'].geometry}
    material={materials['02_-_Default']}
  />
</group>

 const can3 = <group
  position={[45.133, 0, 0.242]}
  rotation={[-Math.PI / 2, 0, 0.698]}
  scale={[0.819, 0.819, 1]}>
  <mesh
    castShadow
    receiveShadow
    geometry={nodes['Can002_07_-_Default_0'].geometry}
    material={materials['07_-_Default']}
  />
  <mesh
    castShadow
    receiveShadow
    geometry={nodes['Can002_02_-_Default_0'].geometry}
    material={materials['02_-_Default']}
  />
</group>
const can4 = <group
  position={[140.983, 0, 0.242]}
  rotation={[-Math.PI / 2, 0, Math.PI / 4]}
  scale={[0.819, 0.819, 1]}>
  <mesh
    castShadow
    receiveShadow
    geometry={nodes['Can003_08_-_Default_0'].geometry}
    material={materials['08_-_Default']}
  />
  <mesh
    castShadow
    receiveShadow
    geometry={nodes['Can003_02_-_Default_0'].geometry}
    material={materials['02_-_Default']}
  />
</group>



  return (
    <group {...props} dispose={null} position={[0, -4 ,0]} scale={[0.1,0.1,0.1]}>
        {can2}
    </group>
  )
}

useGLTF.preload('/model/soda_cans.glb')
